on:
    pull_request: null
    push:
        branches:
            - master
            - '*.*'

name: phpunit

jobs:
    phpunit:
        uses: spiral/gh-actions/.github/workflows/phpunit.yml@master
        with:
            extensions: sockets, grpc
            os: >-
                ['ubuntu-latest']
            stability: >-
                ['prefer-stable']
